export const infoExbhitionNames = {
  "symbol": "Symbol",
  "companyName": "Company Name",
  "exchange" : "Exchange",
  "industry": "Industry",
  "website": "Website",
  "description": "Description",
  "CEO": "CEO",
  "securityName": "Security Name",
  "issueType": "Issue Type",
  "sector": "Sector",
  "primarySicCode":"Primary Sic Code",
  "employees": "Employees",
  "address": "Address",
  "address2": "Address 2",
  "state": "State",
  "city": "City",
  "zip": "Zip",
  "country": "Country",
  "phone": "Phone",
};
